### ISSUE TITLE
thelma breaks testinstall.g in GAP

### ISSUE THREAD

**Issue by alex-konovalov** [vlaver/Thelma#4]
One of the requirements for GAP packages is that they should not break tests from the GAP standard testsuite when they are loaded (see "76.18-4 Testing a GAP package with the GAP standard test suite" in https://www.gap-system.org/Manuals/doc/ref/chap76.html#X7C90C8B87BF6EF0B). This is not the case for Thelma: if it is loaded, then running `tst/testinstall.g` from GAP shows a number of diffs (27 in total), for example
```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-q\
uicktest-drop-in/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/install/label/kovacs/GA\
P-pkg-update-stable-snapshot/tst/testinstall/ffe.tst:344
# Input is:
Norm( AsField( GF(8), GF(8) ), GF(2), Z(8) );
# Expected output:
Z(2)^0
# But found:
1
########
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-q\
uicktest-drop-in/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/install/label/kovacs/GA\
P-pkg-update-stable-snapshot/tst/testinstall/ffe.tst:350
# Input is:
Trace( GF(16), Z(4) );
# Expected output:
0*Z(2)
# But found:
0
########
```
They all seem to come from Thelma having a method that shows zero and one of a field differently. This has to be fixed - it is not recommended for a package to change the output of built-in objects defined in the core GAP system. So far it's not obvious to me from the overview that I've posted in #5.

**Comment by alex-konovalov** [comment]
P.S. most likely this will break many other tests, e.g. `tst/teststandard.g`, test of the GAP manual examples, and also tests that are contained in other GAP packages.

**Comment by alex-konovalov** [comment]
Apparently this will by https://github.com/vlaver/Thelma/commit/219b38ffb179b6d9a9aa1e05432b876c53eb3a79#diff-6dc370f80e66d2c325e10934df42f2b0 removing these two lines
```
SetNameObject(0*Z(2),"0");	
SetNameObject(Z(2)^0,"1"); 
```
I will now re-run GAP testsuite with Telma to check that nothing else is broken, then confirm if this issue may be closed.

**Comment by vlaver** [comment]
> Apparently this will by [219b38f#diff-6dc370f80e66d2c325e10934df42f2b0](https://github.com/vlaver/Thelma/commit/219b38ffb179b6d9a9aa1e05432b876c53eb3a79#diff-6dc370f80e66d2c325e10934df42f2b0) removing these two lines
> 
> ```
> SetNameObject(0*Z(2),"0");	
> SetNameObject(Z(2)^0,"1"); 
> ```
> I will now re-run GAP testsuite with Telma to check that nothing else is broken, then confirm if this issue may be closed.

Please note that I already deleted this lines and made the corresponding changes in "tst" files. So this release of Thelma (which is currently uploaded on github) should not break the tests that you have mentioned.

**Comment by alex-konovalov** [comment]
Thanks @vlaver for the fix, it worked!
